export const SITE_TITLE = 'Giancarlo Buomprisco';
export const SITE_DESCRIPTION = 'Software Developer and Founder';
export const SITE_URL = 'https://giancarlobuomprisco.com';
export const AUTHOR = 'Giancarlo Buomprisco';
export const EMAIL = 'contact@giancarlobuomprisco.com';
export const TWITTER_HANDLE = 'gc_psk';
export const TWITTER_URL = `https://twitter.com/${TWITTER_HANDLE}`;
export const LINKEDIN_URL = 'https://www.linkedin.com/in/giancarlobuomprisco/';
export const GITHUB_URL = 'https://github.com/gbuomprisco';
