name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: ${{secrets.GIT_CREDENTIALS}}

      - uses: actions/checkout@v2
        name: Checkout

      - name: install
        run: npm i

      - name: build
        run: npm run build

      - name: deploy
        run: npm run deploy
